### ISSUE TITLE
Type annotation causes spurious mutation in each mutant

### ISSUE THREAD

**Issue by liam-m** [boxed/mutmut#162]
Hi,

I'm trying out mutmut for the first time with my project https://github.com/liam-m/primes.py/.

I'm running `mutmut run --runner "python3 test.py" --paths-to-mutate=primes.py`

Unfortunately I'm getting 100% mutation coverage because every mutant has not 1 but 2 mutations, e.g.:

```
$ mutmut show 2
--- primes.py
+++ primes.py
@@ -15,7 +15,7 @@
     """
 
     def __init__(self) -> None:
-        self.primes: List[int] = []
+        self.primes: List[int] = None
 
     def __contains__(self, item: Any) -> bool:
         """
@@ -31,7 +31,7 @@
         Used in slicing to get a single prime or a sequence of primes
         """
         if isinstance(key, slice):
-            if key.step == 0:
+            if key.step == 1:
                 raise ValueError("slice step cannot be zero")
 
             if all((s is not None for s in [key.start, key.stop, key.step])):

$ mutmut show 90
--- primes.py
+++ primes.py
@@ -15,7 +15,7 @@
     """
 
     def __init__(self) -> None:
-        self.primes: List[int] = []
+        self.primes: List[int] = None
 
     def __contains__(self, item: Any) -> bool:
         """
@@ -152,7 +152,7 @@
     while start < stop:
         yield start
         start += step
-        step = 2+(step&2)
+        step = 2-(step&2)
 
 def sieve_of_atkin(limit: int) -> Sequence[int]:
     """
```

Since it's including the `[]` to `None` change in every mutant, they are all killed. 

It looks like it's getting confused by the type annotation since if I change it to `self.primes = []` then mutmut produces a single mutation per mutant and I can get <100% mutation coverage.

It's faster to run if you modify test.py as follows:

```
--- a/test.py
+++ b/test.py
@@ -596,4 +596,4 @@ class TestFactorisationWithPrimes(unittest.TestCase):
             self.assertEqual(factorise(i), factorise(i, primes=primes))
 
 if __name__ == '__main__':
-    unittest.main()
+    unittest.main(failfast=True)
```

I might make failfast into a command line option for test.py.

**Comment by boxed** [comment]
Yikes! That is a bad bug!

**Comment by boxed** [comment]
I'm almost certain I fixed this. Please give the latest master version a try, and if it works and you need it I can make a release.

**Comment by liam-m** [comment]
Yes that seems to have fixed it! 

> if it works and you need it I can make a release

That would be great, thanks

**Comment by liam-m** [comment]
Sorry, this doesn't seem to have fixed it - the mutants still have the 

```
--- ../primes.py/primes.py
+++ ../primes.py/primes.py
@@ -15,7 +15,7 @@
     """
 
     def __init__(self) -> None:
-        self.primes: List[int] = []
+        self.primes: List[int] = None
```

**Comment by boxed** [comment]
:(

**Comment by boxed** [comment]
I had time to check this again. And I can't reproduce this on the your code base.

For my future reference I had to run `mutmut run --paths-to-mutate=primes.py --runner="python -m pytest test.py -x --assert=plain"` to run the tests.
