### ISSUE TITLE
pyproject paths incorrectly parsed

### ISSUE THREAD

**Issue by MaxenceG2M** [boxed/mutmut#350]
Hi everyone,

Unfortunately, I can't get mutmut to work: it seems that the paths indicated in `pyproject.toml` are not correctly analyzed.
When I lauch mutmut, it scan ALL python files on my computer...

Context:
- I use [uv](https://github.com/astral-sh/uv) to handle my packages with a `pyproject.toml` file.
- I use unitest for my tests.

My `pyproject.toml` mutmut section:

```toml
[tool.mutmut]
paths_to_mutate = "project1/"
tests_dir = "tests/"
runner = "runner=python -m unittest discover -b -t tests/ -p '*_test.py' tests/"
debug = true
```

A run of mutmut with this:
```sh
$ ./.venv/bin/mutmut run
⠋ Generating mutants/etc/python3.8/sitecustomize.py
/etc/python3.10/sitecustomize.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/pending_page.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/add_remote_dialog.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/select_page.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/data_subpage.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/properties_page.py
/var/lib/flatpak/app/io.github.flattool.Warehouse/x86_64/stable/afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640/files/share/warehouse/Warehouse/file_install_dialog.py
[...]
```

(you can found this exemple here: https://github.com/MaxenceG2M/mutmut-pyproject).

**Comment by MaxenceG2M** [comment]
When I take a closer look, I see that the [walk method](https://github.com/boxed/mutmut/blob/862755df8f59eef3860e8b4c40c1ce4d26cc76ab/mutmut/__main__.py#L153-L157) has a bad behavior.

With my config, the `path` in the `for` loop take respectivly theses values:
- p
- r
- o
- [...]
- 1
- /

Problem seems located here:
https://github.com/boxed/mutmut/blob/862755df8f59eef3860e8b4c40c1ce4d26cc76ab/mutmut/__main__.py#L1021-L1024

But I can't figure how to fix it :(

**Comment by boxed** [comment]
Ah, nice clue there! I have pushed a fix to main that I think will fix this. Can you try it out?

**Comment by MaxenceG2M** [comment]
Unfortunately that doesn't solve the problem :(

The solution is much simpler, and the problem stems from my ignorance of toml!
I just have to use an **array of path** instead a single string, e.g.:

```toml
[tool.mutmut]
paths_to_mutate = [ "project1/" ]
tests_dir = [ "tests/" ]
```

I'm going to propose a pull request to clarify the documentation.
