### ISSUE TITLE
Mutmut 3.3.0 stalls during mutant generation

### ISSUE THREAD

**Issue by CyberiaResurrection** [boxed/mutmut#412]
Mutmut version: 3.3.0
Python version: 3.9.21
OS: Fedora Linux 41

Repo: https://github.com/makhidkarun/traveller_pyroute 

pyproject.toml bits:
```
[tool.mutmut]
paths_to_mutate = ["PyRoute/Outputs/SubsectorMap.py"]
tests_dir = ["Tests/"]
runner = "pytest -x"
```

After installing mutmut and launching it with **mutmut run**, mutmut launches, prints "Generating mutants" and then just sits there until I kill the process, whether a minute or an hour later.

Plain **pytest** runs to completion, as I thought it might be an issue with pytest config, but it doesn't look like it.

What am I doing wrong?

EDIT:
Setting the **paths_to_mutate** to ["PyRoute/Outputs/Colour.py"] (which doesn't seem to generate _any_ mutants) resulted in mutant generation being done in 22 milliseconds, stats run being done, clean test run is done, and the forced fail test fails with "FAILED: Unable to force test failures"

**Comment by Otto-AA** [comment]
Can you run it with debug=true in pyproject.toml and --max-children 1? Then it should print out for which file it is currently generating mutants and you'll know where it gets stuck. Also you could check the stacktrace when doing Ctrl+C, I think this should point to the stuck code.

And "paths_to_mutate" is supposed to be a list of the root directories of your code, not individual files. Likely PyRoute in your case.

**Comment by Otto-AA** [comment]
Thanks for the details. The string escape sequences are fixed on the master branch, but not yet in a release. (See #396 and related issues). You could try it from the master branch (git clone. Then pip install -e /path/to/mutmut should work I think)

> It's been stalled on the Canonicalisation invalid-syntax error for over an hour now, presumably due to the only child I've allowed coughing and dying. If that is true, why did mutant gen continue beyond route.py ?

It's weird behaviour that an error does not stop the mutant generation, likely a side effect of the process pool. If possible we should change that (PRs are welcome if you're interested, though I myself will be gone for some weeks). Not sure why it gets stuck, I'd need to debug that more

**Comment by CyberiaResurrection** [comment]
Thanks for your help and pointers, @Otto-AA  - the git HEAD commit seems to have resolved stalls during mutant generation.  Still not testing mutants tho - that will be a different issue.
